
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    operator: keepalived-operator
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: https
      scheme: https
      tlsConfig:
        ca:
          secret:
            key: 'tls.crt'
            name: keepalived-operator-certs
            optional: false
        serverName: $(METRICS_SERVICE_NAME).$(METRICS_SERVICE_NAMESPACE).svc
  selector:
    matchLabels:
      operator: keepalived-operator
