# Adds namespace to all resources.
namespace: keepalived-operator

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
- ../../default
- ./service-account.yaml


patchesJson6902:
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
    name: keepalived-operator-mutating-webhook-configuration
  path: ./ca-injection.yaml
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: keepalived-operator-validating-webhook-configuration
  path: ./ca-injection.yaml
- target:
    group: ""
    version: v1
    kind: Service
    name: keepalived-operator-webhook-service
  path: ./secret-injection.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: keepalived-operator-controller-manager
  path: ./replace-image.yaml       